package com.aisuluaiva.android.accessibility.feedback

object AppConstants {
const val SHARED_PREFERENCES = "AppSettings"
const val PREFS_SOUND_BOOL = "sound"
const val PREFS_VIBRATION_BOOL = "vibration"
const val PREFS_SOUND_VOLUME_FLOAT = "sound_volume"
const val PREFS_RESOURCES_STRING = "resources"
const val PREFS_BACKLIGHT_IS_ENABLED = "screen_backlight"
const val PREFS_CURRENT_NAV_TYPE = "current_nav_type"
const val PREFS_NAV_TYPES = "nav_types"
const val PREFS_FOCUS_COLOR_INT = "focus_color"
const val PREFS_FOCUS_THICKNESS_INT = "focus_thickness"
const val PREFS_QUICK_MENU_ITEMS = "quick_menu_items"
const val PREFS_SPEECH_RATE_FLOAT = "speech_rate"
const val PREFS_ENGINE_PACKAGE_STR = "preferred_engine"
const val INTENT_SPEECH_RATE_CHANGED = "speech_rate_changed"
const val EXTRA_SPEECH_RATE = "EXTRA_SPEECH_RATE"
const val PREFS_SPEAK_WINDOW_TITLES_BOOL = "speak_window_titles"
const val PREFS_SPEAK_NODE_TYPES_BOOL = "speak_node_types"
const val PREFS_MOVE_TO_ANOTHER_WINDOW_BOOL = "move_to_another_window"
const val INTENT_SPOKEN_LANGUAGE = "spoken_language"
const val EXTRA_LANGUAGE = "EXTRA_LANGUAGE"
const val PREFS_SPEAK_PASSWORDS_AS_YOU_TYPE_BOOL = "speak_passwords_as_you_type"
const val PREFS_SPEAK_PANE_TITLES_BOOL = "speak_pane_titles"
const val PREFS_SPEAK_NODE_IDS_BOOL = "speak_node_ids"
const val PREFS_ANNOUNCE_TIME_WHEN_SCREEN_TURNS_ON_BOOL = "announce_time_when_screen_turns_on"
const val PREFS_ANNOUNCE_DATE_WHEN_SCREEN_TURNS_ON_BOOL = "announce_date_when_screen_turns_on"
const val PREFS_NOTIFY_ABOUT_SCREEN_ORIENTATION_CHANGE_BOOL = "notify_about_screen_orientation_change"
const val PREFS_NOTIFY_WHEN_SCREEN_TURNS_OFF_BOOL = "notify_when_screen_turns_off"
const val PREFS_SPEAK_BATTERY_LEVEL_BOOL = "speak_battery_level"
}
